### ISSUE TITLE
ASGI | Fastapi headers all return null

### ISSUE THREAD

**Issue by cplmayo** [mliezun/caddy-snake#17]
Doing some basic testing with fastapi today and was unable to get request headers using the documented way in fastapi.

```
@app.get("/", response_class=HTMLResponse)
@htmx("index", "index")
async def root_page(request: Request, user_agent: str = Header(None)):
    print(user_agent)
    if request.method == "GET":
        return {"user_agent": user_agent}
```

When run using uvicorn I get the expected string however if executed through caddy-snake results in nulls. I tried multiple methods to extract the headers but always returned null.

**Comment by mliezun** [comment]
Hi @cplmayo! Thanks for failing the issue 🙏

I was able to reproduce and fix the problem in PR #18 

Can you confirm that it solves the problem on your side also?

You can build from a branch doing:

```
CGO_ENABLED=1 xcaddy build --with github.com/mliezun/caddy-snake@asgi-lowercase-headers
```

**Comment by cplmayo** [comment]
It is working for me; thank you for pushing this so quickly.

**Comment by mliezun** [comment]
Awesome! Thanks for testing it.

I'll merge and close the issue 👌
