### ISSUE TITLE
build constraints exclude all Go files in ...

### ISSUE THREAD

**Issue by tctlrd** [mliezun/caddy-snake#36]
I receive this error when attempting to build with xcaddy:

[INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/mliezun/caddy-snake github.com/caddyserver/caddy/v2 
go: added github.com/mliezun/caddy-snake v0.0.7
[INFO] exec (timeout=0s): /usr/bin/go get -d -v  
[INFO] Build environment ready
[INFO] Building Caddy
[INFO] exec (timeout=0s): /usr/bin/go mod tidy -e 
[INFO] exec (timeout=0s): /usr/bin/go build -o /home/build/caddy -ldflags -w -s -trimpath -tags nobadger 
package caddy
	imports github.com/mliezun/caddy-snake: build constraints exclude all Go files in /home/build/go/pkg/mod/github.com/mliezun/caddy-snake@v0.0.7

**Comment by mliezun** [comment]
Hi @tctlrd!

Have you tried compiling with CGO enabled?

If not, this command should work:

```
CGO_ENABLED=1 xcaddy build --with github.com/mliezun/caddy-snake
```

**Comment by tctlrd** [comment]
@mliezun
Thanks for the reply!
No I have not. I will try that.

**Comment by mliezun** [comment]
Cool, let me know if it works!

**Comment by mliezun** [comment]
If it's fixed we should close this issue

**Comment by tctlrd** [comment]
I tried it tonight and it worked with CGO_ENABLED=1. Thank you for your help and sharing this module!
