### ISSUE TITLE
How do you define the path to the python app?  

### ISSUE THREAD

**Issue by calebcall** [mliezun/caddy-snake#42]
Do we need to set an env variable such as PYTHONPATH, HOME, etc to the app path?

**Comment by mliezun** [comment]
Hi @calebcall!

The path to the python app is set with the module_wsgi or module_asgi directives in the Caddyfile.

You can create a Caddyfile in the root of your project, point to your app inside the file as you'd do with other standard web servers like gunicorn. 

Then run caddy with that config.

It's also possible to set a venv using the "venv_path" directive.

**Comment by mliezun** [comment]
The `tests` folder contains apps used for integration tests. This is how a Flask app is configured for example: https://github.com/mliezun/caddy-snake/tree/main/tests/flask
