### ISSUE TITLE
ASGI support for FastAPI

### ISSUE THREAD

**Issue by nickchomey** [mliezun/caddy-snake#5]
This is fantastic! But I'm wondering if there's any sort of ASGI support, in order to run FastAPI apps?

Or am I misunderstanding how this all works and there's another approach for this?

**Comment by mliezun** [comment]
Hi @nickchomey!

Caddy snake doesn't have ASGI support yet. But this project might be useful to run ASGI apps with a WSGI server: https://github.com/abersheeran/a2wsgi.

I tested with a simple FastAPI app and seems to work:

**example_fastapi.py**
```python
from fastapi import FastAPI
from a2wsgi import ASGIMiddleware

app = FastAPI()

@app.get("/app")
async def root():
    return {"message": "Hello World"}


app = ASGIMiddleware(app)
```

**Caddyfile**
```
{
	http_port 9080
	https_port 9443
	log {
		level info
	}
}
localhost:9080 {
	route /app {
		python "example_fastapi:app"
	}
}
```

I think this is just a workaround for now.

Thanks for your comments and for filing the issue. And hope this helps. Im gonna start working on ASGI support as soon as possible

**Comment by mliezun** [comment]
This plugin is meant to avoid adding an extra layer of reverse proxy. What the plugin is doing is embedding the Python interpreter inside Caddy. It doesn't create a new process on each request. The requests are all handled within Caddy.

To make it clear, when you configure a Caddyfile like this:

```Caddyfile
route /app {
    python "example_fastapi:app"
}
```

What happens internally is that Caddy imports the FastAPI app using the [Python C API](https://docs.python.org/3/c-api/index.html) and is initialized on startup, the FastAPI server runs inside Caddy from then on.

On each request to `/app`, Caddy passes the data directly to FastAPI "in-memory" without creating a new process.

**Comment by mliezun** [comment]
Yep, exactly like that.

It serves the same purpose as gunicorn/uvicorn.

And indeed this plugin works similarly as Frankenphp replacing the php-fpm calls.

**Comment by mliezun** [comment]
Thank you!

I'm here to help, don't hesitate in asking other questions if further clarification is needed.

**Comment by mliezun** [comment]
ASGI HTTP support is out!

There's a new directive to use it: `module_asgi`.

You can import your apps as follows:

```Caddyfile
route /app {
  python {
    module_asgi "example_fastapi:app"
  }
}
```

This doesn't require any external dependencies and should work out of the box. 

Noting here that it only supports HTTP for now, Websockets is not supported yet.
